### ISSUE TITLE
Supported Apps

### ISSUE THREAD

**Issue by nvzqz** [savoryink/setfont#1]
Each app has its own way of setting fonts, which can vary across operating systems. Apps this tool supports are tracked here.

## macOS

- [ ] Alacritty (`alacritty`, #9)
- [ ] Atom (`atom`, #12)
- [ ] iTerm (`iterm`, #8)
- [ ] Sublime Text (`sublimetext`, #10)
- [ ] Terminal (`terminal`, #3)
- [ ] Visual Studio Code (`vscode`, #7)
- [ ] Xcode (`xcode`, #2)

## Linux

- [ ] Alacritty (`alacritty`, #9)
- [ ] Atom (`atom`, #12)
- [ ] GNOME Terminal (`terminal`, #14)
- [ ] Konsole (`konsole`, #15)
- [ ] Sublime Text (`sublimetext`, #10)
- [ ] rxvt Terminal (`rxvt`, #5)
- [ ] rxvt-unicode Terminal (`urxvt`, #6)
- [ ] Terminator (`terminator`, #13)
- [ ] Tilix (`tilix`, #11)
- [ ] Visual Studio Code (`vscode`, #7)

## Windows

- [ ] Alacritty (`alacritty`, #9)
- [ ] Atom (`atom`, #12)
- [ ] Sublime Text (`sublimetext`, #10)
- [ ] Terminal (`terminal`, #4)
- [ ] Visual Studio Code (`vscode`, #7)
